spring:
  profiles:
    group:
      local: local
      prod: prod
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: ha
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    show_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mydatabase.czogkye88fqc.ap-northeast-2.rds.amazonaws.com:3306/seoul
    username: artrium
    password: 12345678
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    show_sql: true
    defer-datasource-initialization: true
    generate-ddl: true
server:
  port: 8080

logging:
  file:
    name: logs/application.log
  level:
    root: warn
  logback:
    rollingpolicy:
      clean-history-on-start: true
